# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_vote.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import interfaces.vote_option_pb2 as vote__option__pb2
import interfaces.gogo_pb2 as gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emsg_vote.proto\x12\x12\x63osmos.gov.v1beta1\x1a\x11vote_option.proto\x1a\ngogo.proto\"\x81\x01\n\x07MsgVote\x12\x13\n\x0bproposal_id\x18\x01 \x01(\x04\x12\x1f\n\x05voter\x18\x02 \x01(\tB\x10\xf2\xde\x1f\x0cyaml:\"voter\"\x12.\n\x06option\x18\x03 \x01(\x0e\x32\x1e.cosmos.gov.v1beta1.VoteOption:\x10\xe8\xa0\x1f\x00\x98\xa0\x1f\x00\x80\xdc \x00\x88\xa0\x1f\x00\x42\x32Z0github.com/cosmos/cosmos-sdk/x/gov/types/v1beta1b\x06proto3')



_MSGVOTE = DESCRIPTOR.message_types_by_name['MsgVote']
MsgVote = _reflection.GeneratedProtocolMessageType('MsgVote', (_message.Message,), {
  'DESCRIPTOR' : _MSGVOTE,
  '__module__' : 'msg_vote_pb2'
  # @@protoc_insertion_point(class_scope:cosmos.gov.v1beta1.MsgVote)
  })
_sym_db.RegisterMessage(MsgVote)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/cosmos/cosmos-sdk/x/gov/types/v1beta1'
  _MSGVOTE.fields_by_name['voter']._options = None
  _MSGVOTE.fields_by_name['voter']._serialized_options = b'\362\336\037\014yaml:\"voter\"'
  _MSGVOTE._options = None
  _MSGVOTE._serialized_options = b'\350\240\037\000\230\240\037\000\200\334 \000\210\240\037\000'
  _MSGVOTE._serialized_start=70
  _MSGVOTE._serialized_end=199
# @@protoc_insertion_point(module_scope)
