# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_send_to_eth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import interfaces.gogo_pb2 as gogo__pb2
import interfaces.coin_pb2 as coin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15msg_send_to_eth.proto\x12\ngravity.v1\x1a\ngogo.proto\x1a\ncoin.proto\"\x96\x01\n\x0cMsgSendToEth\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08\x65th_dest\x18\x02 \x01(\t\x12/\n\x06\x61mount\x18\x03 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00\x12\x33\n\nbridge_fee\x18\x04 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00\x42\x41Z?github.com/Gravity-Bridge/Gravity-Bridge/module/x/gravity/typesb\x06proto3')



_MSGSENDTOETH = DESCRIPTOR.message_types_by_name['MsgSendToEth']
MsgSendToEth = _reflection.GeneratedProtocolMessageType('MsgSendToEth', (_message.Message,), {
  'DESCRIPTOR' : _MSGSENDTOETH,
  '__module__' : 'msg_send_to_eth_pb2'
  # @@protoc_insertion_point(class_scope:gravity.v1.MsgSendToEth)
  })
_sym_db.RegisterMessage(MsgSendToEth)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z?github.com/Gravity-Bridge/Gravity-Bridge/module/x/gravity/types'
  _MSGSENDTOETH.fields_by_name['amount']._options = None
  _MSGSENDTOETH.fields_by_name['amount']._serialized_options = b'\310\336\037\000'
  _MSGSENDTOETH.fields_by_name['bridge_fee']._options = None
  _MSGSENDTOETH.fields_by_name['bridge_fee']._serialized_options = b'\310\336\037\000'
  _MSGSENDTOETH._serialized_start=62
  _MSGSENDTOETH._serialized_end=212
# @@protoc_insertion_point(module_scope)
